DROP TABLE  IF EXISTS languages CASCADE;

DROP TABLE IF EXISTS all_themes CASCADE;

DROP TABLE IF EXISTS files CASCADE;

DROP TABLE IF EXISTS users CASCADE;

DROP TABLE IF EXISTS transcripts CASCADE;
